### PR TITLE
fix(app): update cancellation policy modal

### LINKED ISSUE #380: Cancellation policy is unclear
The policy is:
> Please note the cancellation policy before committing to a reservation.
>
> Booking canceled a week before: 50% refund.
> Booking canceled a day before: 25% refund.
> Booking canceled in the last 24 hours: 10% refund.

What does that mean? If I cancel the booking month before the event will I be 100% refunded or just 50%? Booking canceled a day before is the same as 24 hours before, isn't it?

Shouldn't it be something like:

> Any cancellation more than a 7 days prior to checkin date will be refunded by 50% of the price of booking.
> Any cancellation between a 7 and 1 day before checking date will be refunded by 25% of the price of booking.
> Any cancellation less than 1 day before checking will be refunded by 10% of the price of booking.
> Cancellation past the booking time is not possible.

### PR DESCRIPTION
**Pull request by PabloAlice**
fix #380

### CODE REVIEW

File: app/src/sections/Booking/FormSection/CancellationPolicyModal.jsx [hunk 1]
```diff
@@ -15,36 +15,27 @@ Hotel cancellation & refund policy
...
 
           <ul>
-            <li>
-              <b>
-Booking canceled a week before:
-              </b>
-              {' '}
-50% refund.
+            <li className="mb-1">
+              Any cancellation more than a 7 days prior to checkin date will be refunded
```
Comment (MatiasOS) [inline app/src/sections/Booking/FormSection/CancellationPolicyModal.jsx]: here is a typo `checkinG`
