### PR TITLE
Fix/validate eth address

### LINKED ISSUE #165: guest eth address
We need to validate checksum address to prevent possible human errors.

### PR DESCRIPTION
**Pull request by MatiasOS**
Validate address in server-side. This closes #165

### CODE REVIEW

File: server/src/errors/codes.js [hunk 1]
```diff
@@ -46,6 +46,11 @@ module.exports = {
     short: 'No guest Ethereum address provided.',
     long: 'The field guestEthAddress is required.',
   },
+  guestEthAddressChecksum: {
+    status: 409,
+    short: 'Ivaliid guest Ethereum address.',
```
Comment (beogip) [inline server/src/errors/codes.js]: I think there is a typo
